# Numpy

## List vs Array

- liste Python, c'est comme une boite a outils. Chaque element est independant, donc les ranger prend du temps.
- Un array Numpy (ndarray), c'est un tournevis electrique. Operations se font ensemble,
d'un coup, en masse.

## Installation et vérification

In [ ]:
# dans le terminal : pip install numpy
# dans une cellule notebook : !pip install numpy
# Pour un reinstall propre forcé : pip install --force-reinstall --no-cache-dir numpy
# python -m pip install numpy
import numpy as np

# verification
print(np.__version__)

2.4.3


## Creation d'arrays et attributs

In [9]:
l = [1,2,3,4,5,6,7,8,9]
a = np.array(l)

print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)


In [10]:
l = [1,2,3,4,5.4,6,7,8,9]
a = np.array(l)
print(a)

[1.  2.  3.  4.  5.4 6.  7.  8.  9. ]


In [11]:
np.array([1.5,1,True,False, "azerty"])

array(['1.5', '1', 'True', 'False', 'azerty'], dtype='<U32')

In [14]:
liste = [1,2,3,4,5]
a = np.array([1,2,3,4,5])

#operation sur la liste
print([x*2 for x in liste])

# operation sur array
print(a * 2)

[2, 4, 6, 8, 10]
[ 2  4  6  8 10]


## Difference de vitesse

In [18]:
import time
liste = list(range(10_000_000))
a = np.arange(10_000_000)

#liste
t0 = time.perf_counter()
resultat_liste = [x*2 for x in liste]
t1 = time.perf_counter()

#array
t2 = time.perf_counter()
resultat_array = a * 2
t3 = time.perf_counter()

print(f"Liste Python : {(t1 - t0)*1000:.2f} ms")
print(f"NumPy        : {(t3 - t2)*1000:.2f} ms")
print(f"Accélération : {(t1 - t0)/(t3 - t2):.1f}x")

Liste Python : 811.78 ms
NumPy        : 34.51 ms
Accélération : 23.5x


## Les fonctions constructeurs

In [37]:
print(f"np.arange(10) = {np.arange(10)}")
print(f"np.arange(2, 10, 2) = {np.arange(2, 10, 2)}")

print(f"np.zeros(5) = {np.zeros(5)}")
print(f"np.ones(5) = {np.ones(5)}")
print(f"np.ones(5) = \n{np.ones((3,4))}")

# points egalement espacés
print(f"np.linspace(0, 100, 5) = {np.linspace(0, 100, 5)}")

#reshape
print(f"{np.arange(12).reshape(3, 4)}")

#
print(np.arange(12).reshape(1,12).shape)

np.arange(10) = [0 1 2 3 4 5 6 7 8 9]
np.arange(2, 10, 2) = [2 4 6 8]
np.zeros(5) = [0. 0. 0. 0. 0.]
np.ones(5) = [1. 1. 1. 1. 1.]
np.ones(5) = 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
np.linspace(0, 100, 5) = [  0.  25.  50.  75. 100.]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(1, 12)


## les attributs

In [47]:
a = np.arange(24).reshape(4,6)
print(a)
print(f"Forme : {a.shape}")
print(f"Nombre dimensions : {a.ndim}")
print(f"Type : {a.dtype}")
print(f"Taille : {a.size}")
print(f"Taille element : {a.itemsize}")
print(f"Memoire totale : {a.nbytes}")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Forme : (4, 6)
Nombre dimensions : 2
Type : int64
Taille : 24
Taille element : 8
Memoire totale : 192


## Génération aléatoire

In [56]:
rng = np.random.default_rng(42)
print(rng.random(5))
print(rng.integers(0, 21, 10))
print(rng.normal(12, 3, 20))

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[11 20 15 15 15 16 10  2 17  9]
[14.63819392 14.33337581 12.19809209 15.38172362 13.40252803  9.42212261
 13.10625235  9.1233522  14.6353509  11.85022227 11.44541291  9.95721137
 15.66762402 11.53641155 10.71501653 10.94359935 13.59692756 13.09633219
 13.23819783 13.29246301]


## Exercice 1

In [ ]:
# 1. Créer un array à partir de [5, 10, 15, 20, 25, 30]
# 2. Afficher sa forme, son nombre de dimensions, son type
# 3. Créer un array de 0 à 20 (exclu) avec arange
# 4. Créer un vecteur de 10 zéros
# 5. Créer une matrice de 1 de forme 3×4
# 6. Créer un vecteur de 7 points équidistants entre 0 et 1
# 7. Créer un tableau 5×5 rempli de nombres aléatoires entiers entre 1 et 100 inclu